### ISSUE TITLE
[influxdb.clj] SSLSocketfactory not supported on JDK 9+

### ISSUE THREAD

**Issue by vipinvkmenon** [riemann/riemann#1007]
**Describe the bug**
We are trying to  upgrade the JVM version (like: either 1.8.0_312 or 16.0.1) , however, we get the exception 
` java.lang.UnsupportedOperationException: clientBuilder.sslSocketFactory(SSLSocketFactory) not supported on JDK 9+`

Initially, we thought it may be due to the older version of riemann being used, however, upgrading to riemann `0.3.8` also throws the same exception.
Trace:
```
clojure.lang.Compiler$CompilerException: java.lang.UnsupportedOperationException: clientBuilder.sslSocketFactory(SSLSocketFactory) not supported on JDK 9+, compiling:(endpoints.clj:80:12)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3700)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3694)
	at clojure.lang.Compiler$IfExpr.eval(Compiler.java:2722)
	at clojure.lang.Compiler$DefExpr.eval(Compiler.java:457)
	at clojure.lang.Compiler.eval(Compiler.java:7067)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	at clojure.lang.Compiler.loadFile(Compiler.java:7452)
	at clojure.lang.RT$3.invoke(RT.java:325)
	at riemann.config$include.invokeStatic(config.clj:467)
	at riemann.config$include.invoke(config.clj:444)
	at riemann.config$eval261.invokeStatic(riemann.config:6)
	at riemann.config$eval261.invoke(riemann.config:6)
	at clojure.lang.Compiler.eval(Compiler.java:7062)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	at clojure.lang.Compiler.loadFile(Compiler.java:7452)
	at clojure.lang.RT$3.invoke(RT.java:325)
	at riemann.config$include.invokeStatic(config.clj:467)
	at riemann.config$include.invoke(config.clj:444)
	at riemann.bin$_main$fn__14793.invoke(bin.clj:147)
	at riemann.bin$run_app_BANG_.invokeStatic(bin.clj:131)
	at riemann.bin$run_app_BANG_.invoke(bin.clj:123)
	at riemann.bin$_main.invokeStatic(bin.clj:147)
	at riemann.bin$_main.doInvoke(bin.clj:135)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at riemann.bin$_main.invokeStatic(bin.clj:140)
	at riemann.bin$_main.invoke(bin.clj:135)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at riemann.bin.main(Unknown Source)
Caused by: java.lang.UnsupportedOperationException: clientBuilder.sslSocketFactory(SSLSocketFactory) not supported on JDK 9+
	at okhttp3.internal.platform.Jdk9Platform.trustManager(Jdk9Platform.kt:61)
	at okhttp3.OkHttpClient$Builder.sslSocketFactory(OkHttpClient.kt:751)
	at riemann.influxdb$get_builder.invokeStatic(influxdb.clj:78)
	at riemann.influxdb$get_builder.invoke(influxdb.clj:73)
	at riemann.influxdb$get_client.invokeStatic(influxdb.clj:89)
	at riemann.influxdb$get_client.invoke(influxdb.clj:85)
	at riemann.influxdb$influxdb_deprecated.invokeStatic(influxdb.clj:261)
	at riemann.influxdb$influxdb_deprecated.invoke(influxdb.clj:246)
	at riemann.influxdb$influxdb.invokeStatic(influxdb.clj:306)
	at riemann.influxdb$influxdb.invoke(influxdb.clj:271)
	at riemann.config$fn__407$fn__408.invoke(endpoints.clj:85)
	at riemann.config$fn__407.invokeStatic(endpoints.clj:80)
	at riemann.config$fn__407.invoke(endpoints.clj:80)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3695)
	... 28 common frames omitted
```
endpoints.clj calls influxdb like :
```
(def influx
    (batch 5000 1
           (exception-stream handle-exceptions
                             (async-queue! :influxdb3-queue
                                           {:1e4 1e4
                                            :max-pool-size rt-config/available-processors
                                            :core-pool-size rt-config/available-processors}
                                           (let [influxdbx (influxdb   { :host <host>
                                                                                       :scheme "https"
                                                                                       :username <username>
                                                                                       :password <password>
                                                                                       :db ("db")
                                           ;--TODO: How to pass certificates--
                                                                                       :insecure true})]
                                             (  ; prn
                                              influxdbx))))
```
influxdb is configured with "https" and therefore the configuration is as such.

**To Reproduce**
1. Run riemann with influxdb and java newer versions.
2. Write a script that sends data influxdb with https. (or simply mimic it with socat `nohup socat -v OPENSSL-LISTEN:8086,cert=/tmp/monitoring/client.crt,key=/tmp/monitoring/client.key,cafile=/tmp/monitoring/ca.crt,verify=0,fork 'SYSTEM:/bin/echo HTTP/1.1 200 OK;' >NC_OUTPUT 2>&1 &`
3. See error: `java.lang.UnsupportedOperationException`

**Expected behavior**
It works with newer version of java.
 
This issue is only seen when Riemann runs with a newer version of Java. If an older version of Java is used like `jdk8u192` riemann works smoothly. 

**Background (please complete the following information):**
 - OS: ubuntu 20.04
 - Java/JVM version: 1.8.0_312 `openjdk version "1.8.0_312" OpenJDK Runtime Environment (build 1.8.0_312-8u312-b07-0ubuntu1~20.04-b07)`
 - Riemann version: 0.3.8

**Additional context**
All code works smoothly on an older version of java however breaks on upgrading JDK.... using the newer version of riemann as wel.. 0.3.8

The issue seems I suspect to be coming from influxdb.clj----> [okhttp3.ClientBuilder](https://github.com/riemann/riemann/blob/main/src/riemann/influxdb.clj#L73-L83). Seems like this area of code hasn't been updated or changed in a while.
Additionally we use influx 1.7 & 1.8 (not influx 2 style).

**Comment by chhetripradeep** [comment]
Hi @vipinvkmenon 

Thank you for reporting the issue.  Can you try building from this PR branch: https://github.com/riemann/riemann/pull/1008 and validate if it resolves the issue for you. Let us know how it goes.
