### ISSUE TITLE
Graphite UDP server gets ClassCastException

### ISSUE THREAD

**Issue by benbc** [riemann/riemann#509]
Hello

I'm trying to use Riemann as a proxy in front of Graphite. At the moment I'm just passing straight through to Graphite. Here is my config:

    (logging/init {:file "/var/log/riemann/riemann.log"})

    (let [host "0.0.0.0"]
      (graphite-server {:host host :protocol :tcp})
      (graphite-server {:host host :protocol :udp}))

    (streams
      (graphite {:host "127.0.0.1" :port 2005}))

The TCP server works fine, but the UDP server gives this error every time it gets a message:

    WARN [2015-02-05 15:25:21,698] defaultEventExecutorGroup-2-1 - riemann.transport.udp - UDP handler caught
    io.netty.handler.codec.DecoderException: java.lang.RuntimeException: Graphite server parse error (java.lang.ClassCastException: io.netty.channel.socket.DatagramPacket cannot be cast to java.lang.CharSequence): #<DatagramPacket DatagramPacket(/172.28.128.1:51160 => /0:0:0:0:0:0:0:0:2003, UnpooledUnsafeDirectByteBuf(ridx: 0, widx: 2048, cap: 2048))>
            at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99)
            at riemann.transport.graphite.proxy$io.netty.handler.codec.MessageToMessageDecoder$ff19274a.channelRead(Unknown Source)
            at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
            at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
            at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
            at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
            at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
            at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:166)
            at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
            at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
            at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
            at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93)
            at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
            at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
            at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
            at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
            at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
            at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
            at java.lang.Thread.run(Thread.java:745)
    Caused by: java.lang.RuntimeException: Graphite server parse error (java.lang.ClassCastException: io.netty.channel.socket.DatagramPacket cannot be cast to java.lang.CharSequence): #<DatagramPacket DatagramPacket(/172.28.128.1:51160 => /0:0:0:0:0:0:0:0:2003, UnpooledUnsafeDirectByteBuf(ridx: 0, widx: 2048, cap: 2048))>
            at riemann.transport.graphite$graphite_frame_decoder$fn__5167.invoke(graphite.clj:89)
            at riemann.transport.graphite.proxy$io.netty.handler.codec.MessageToMessageDecoder$ff19274a.decode(Unknown Source)
            at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89)
            ... 18 more

Any idea what is going wrong?

Thanks
-Ben

**Comment by bamdadd** [comment]
I'm getting the same error on UDP. Did you manage to fix this?

**Comment by dlecocq** [comment]
Also experienced this.

**Comment by mcorbin** [comment]
I tried to solve this issue, my fix seems to work but i don't know netty and riemann internal well so i probably missed something.

[here](https://github.com/riemann/riemann/blob/master/src/riemann/transport/graphite.clj#L83), with grapĥite in udp mode message is a io.netty.channel.socket.DatagramPacket and not a string => ClassCastException.

I took inspiration from [here](https://github.com/riemann/riemann/blob/master/src/riemann/transport.clj#L120), but i don't know if i need to call retain or not.

@pyr i need help on this one ;)
