### ISSUE TITLE
Sending reserved protocol-buffer fields results in weird behaviour

### ISSUE THREAD

**Issue by faxm0dem** [riemann/riemann#545]
When sending reserved keys as attributes in the protobuf payload, e.g. `attribute[tags] = a,b,c,d`  or `attribute[metric] = 123` results in bad things: client queries freeze, and errors appear in the server during the query. Here's an example for the `tags` attribute:

```
WARN [2015-04-10 12:23:37,718] pool-19-thread-12 - riemann.streams - riemann.streams$forward$stream__4775@3e29a694 threw
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Iterable
        at riemann.codec$encode_pb_event.invoke(codec.clj:79)
        at riemann.codec$encode_client_pb_event.invoke(codec.clj:95)
        at clojure.core$map$fn__4245.invoke(core.clj:2557)
        at clojure.lang.LazySeq.sval(LazySeq.java:40)
        at clojure.lang.LazySeq.seq(LazySeq.java:49)
        at clojure.lang.LazySeq.iterator(LazySeq.java:184)
        at com.google.protobuf.AbstractMessageLite$Builder.checkForNullValues(AbstractMessageLite.java:336)
        at com.google.protobuf.AbstractMessageLite$Builder.addAll(AbstractMessageLite.java:323)
        at com.aphyr.riemann.Proto$Msg$Builder.addAllEvents(Proto.java:5123)
        at com.aphyr.riemann.client.RiemannClient.sendEvents(RiemannClient.java:129)
        at riemann.client$send_events.invoke(client.clj:64)
        at riemann.streams$forward$stream__4775.invoke(streams.clj:1214)
        at riemann.streams$execute_on$stream__3840$runner__3841$fn__3852.invoke(streams.clj:268)
        at riemann.streams$execute_on$stream__3840$runner__3841.invoke(streams.clj:268)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invoke(core.clj:624)
        at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1862)
        at clojure.lang.RestFn.invoke(RestFn.java:425)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at clojure.core$apply.invoke(core.clj:628)
        at clojure.core$bound_fn_STAR_$fn__4140.doInvoke(core.clj:1884)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

![2015-04-10-124217_1070x903_scrot](https://cloud.githubusercontent.com/assets/112638/7086275/0b4d8b54-df7f-11e4-9446-950581939538.png)

**Comment by pyr** [comment]
hi @faxm0dem, riemann.codec does not handle garbled input perfectly for now.
