### ISSUE TITLE
InvalidProtocolBufferException on big tcp package

### ISSUE THREAD

**Issue by minaevmike** [riemann/riemann#597]
Hello, i send via tcp 140Mb message to riemann and i have such execption
<code>
WARN [2015-08-24 18:36:02,969] defaultEventExecutorGroup-2-1 - riemann.transport.tcp - TCP handler caught
io.netty.handler.codec.DecoderException: com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:161)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
	at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
	at com.google.protobuf.InvalidProtocolBufferException.invalidTag(InvalidProtocolBufferException.java:89)
	at com.google.protobuf.CodedInputStream.readTag(CodedInputStream.java:108)
	at com.aphyr.riemann.Proto$Event.<init>(Proto.java:1575)
	at com.aphyr.riemann.Proto$Event.<init>(Proto.java:1539)
	at com.aphyr.riemann.Proto$Event$1.parsePartialFrom(Proto.java:1684)
	at com.aphyr.riemann.Proto$Event$1.parsePartialFrom(Proto.java:1679)
	at com.google.protobuf.CodedInputStream.readMessage(CodedInputStream.java:309)
	at com.aphyr.riemann.Proto$Msg.<init>(Proto.java:3931)
	at com.aphyr.riemann.Proto$Msg.<init>(Proto.java:3847)
	at com.aphyr.riemann.Proto$Msg$1.parsePartialFrom(Proto.java:3970)
	at com.aphyr.riemann.Proto$Msg$1.parsePartialFrom(Proto.java:3965)
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:141)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:176)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:182)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
	at io.netty.handler.codec.protobuf.ProtobufDecoder.decode(ProtobufDecoder.java:119)
	at io.netty.handler.codec.protobuf.ProtobufDecoder.decode(ProtobufDecoder.java:63)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89)
	... 12 more
</code>
So what i can do?

**Comment by aphyr** [comment]
To be honest, 140 megabytes is a few orders of magnitude larger than Riemann was ever designed to handle, so I'm not exactly sure what you're trying to do here. There might be a bug in Netty, the framing decoder, or the protocol buffer decoder. I would start by writing a reproducible test case and checking whether you it'll pass round-trip serialization correctly, and maybe trying a wireshark capture to see if the message is being corrupted on the wire somehow.

**Comment by minaevmike** [comment]
Thank you. Ok, i won't send so big packets. I found another(bug?). I have default settings for rimann(install from deb). If i send udp package for 2090 bytes, riemann gives me parse error(as i can undestand it read too few bytes) but if i send pacage for 1970 bytes it work's fine. Are you sure thet limit of 16384 is in bytes not in bits??

**Comment by aphyr** [comment]
As far as I know UDP recv buffers are measured in bytes, but again, try a packet capture and see. UDP packets can be truncated by the network at any time.

**Comment by minaevmike** [comment]
i try by nc and i get full packet, but when i send it to riemann it fails 100% with same error(btw i don't have high load)
