### ISSUE TITLE
java.lang.NullPointerException Sending an email

### ISSUE THREAD

**Issue by rubialex** [riemann/riemann#638]
Hi all!

I'm working with munin-tensor-riemann and I'm trying to send an email when there's an specific service but I'm receiving a null pointer exception. 

I've read that it could be because there's not :time or :ttl but there are both (I think so). Here I show you the code:

; -*- mode: clojure; -*-
; vim: filetype=clojure

(logging/init {:file "/var/log/riemann/riemann.log"})

; Listen on the local interface over TCP (5555), UDP (5555), and websockets
; (5556)
(let [host "0.0.0.0"]
  (tcp-server {:host host})
  (udp-server {:host host})
  (ws-server  {:host host}))

; Expire old events from the index every 5 seconds.
(periodically-expire 5)

(let [email (mailer {:host "smtp.gmail.com"
                    :user "alex.latorre.alberich"
                    :pass "********"
 :ssl :yes
}{:from "hola@prueba.com"}) index (index)]
  ; Inbound events will be passed to these streams:
    (streams
        (default :ttl 60
      ; Index all events immediately.
      index
        ;#(info "received event jejeje" %)
        (where (service "mymunin.network.if_eth0.up")
        index
        #(info %)
        (info (email "rubialex17@hotmail.com"))
        (influxdb  {:version :0.9 :host "localhost" :port 8086 :db "riemann" :username "riemann" :password "riemann" :series #(str (:host %) "." (:service %))})
; Log expired events.
      (expired
        (fn [event] (info "expired" event))))
        (where (not(service "mymunin.network.if_eth0.up"))
        (influxdb {:version :0.9 :host "localhost" :port 8086 :db "riemann" :username "riemann" :password "riemann" :series #(str (:host %) "." (:service %)) })))))

And this is what I get:

INFO [2016-01-04 15:56:56,423] defaultEventExecutorGroup-2-2 - riemann.config - #riemann.codec.Event{:host deheremap6787.emea.adsint.biz, :service mymunin.network.if_eth0.up, :state ok, :description Traffic of the eth0 interface. Maximum speed is 10000 Mb/s., :metric 405.7412877764183, :tags [h o l a   c a r a c o l a], :time 1451919411, :ttl 120.0}
WARN [2016-01-04 15:56:56,423] defaultEventExecutorGroup-2-2 - riemann.config -  threw
java.lang.NullPointerException
        at riemann.config$eval57$stream__66$fn__71.invoke(riemann.config:33)
        at riemann.config$eval57$stream__66.invoke(riemann.config:33)
        at riemann.streams$default$stream__5044$fn__5055.invoke(streams.clj:1353)
        at riemann.streams$default$stream__5044.invoke(streams.clj:1353)
        at riemann.core$stream_BANG_$fn__5727.invoke(core.clj:19)
        at riemann.core$stream_BANG_.invoke(core.clj:18)
        at riemann.transport$handle.invoke(transport.clj:159)
        at riemann.transport.tcp$tcp_handler.invoke(tcp.clj:94)
        at riemann.transport.tcp$gen_tcp_handler$fn__5949.invoke(tcp.clj:65)
        at riemann.transport.tcp.proxy$io.netty.channel.ChannelInboundHandlerAdapter$ff19274a.channelRead(Unknown Source)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.access$700(AbstractChannelHandlerContext.java:32)
        at io.netty.channel.AbstractChannelHandlerContext$8.run(AbstractChannelHandlerContext.java:324)
        at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:36)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Thread.java:745)

Thank you so much!

**Comment by jamtur01** [comment]
I think this was answered on the mailing list.

**Comment by pyr** [comment]
answered on ML.
