### ISSUE TITLE
RejectedExecutionException in logs

### ISSUE THREAD

**Issue by cristi-** [riemann/riemann#655]
Hi,
 We have a riemann server that recently started throwing RejectedExecutionException warnings in logs and I am not sure if we are missing events because of this.

`WARN [2016-02-15 02:11:47,700] defaultEventExecutorGroup-2-1 - riemann.config - riemann.streams$execute_on$stream__2580@417fdbe1 threw
java.util.concurrent.RejectedExecutionException: Task clojure.core$bound_fn_STAR_$fn__4140@2613a497 rejected from java.util.concurrent.ThreadPoolExecutor@1d093dd[Running, pool size = 128, active threads = 128, queued tasks = 1000, completed tasks = 51904333]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2048)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:821)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1372)
	at riemann.service.ExecutorServiceService.execute(service.clj:173)
	at riemann.streams$execute_on$stream__2580.invoke(streams.clj:267)
	at riemann.config$eval543$stream__553$fn__558.invoke(riemann.config.clj:49)
	at riemann.config$eval543$stream__553.invoke(riemann.config.clj:49)
	at riemann.config$eval543$stream__598$fn__603.invoke(riemann.config.clj:48)
	at riemann.config$eval543$stream__598.invoke(riemann.config.clj:48)
	at riemann.streams$sdo$stream__2555$fn__2566.invoke(streams.clj:242)
	at riemann.streams$sdo$stream__2555.invoke(streams.clj:242)
	at synygy.riemann.core$severity$fn__82$fn__93.invoke(core.clj:38)
	at synygy.riemann.core$severity$fn__82.invoke(core.clj:38)
	at riemann.config$eval543$splitp_stream__3994__auto____1872.invoke(riemann.config.clj:249)
	at riemann.streams$with$stream__3660$fn__3687.invoke(streams.clj:1304)
	at riemann.streams$with$stream__3660.invoke(streams.clj:1304)
	at riemann.config$eval543$stream__1877$fn__1882.invoke(riemann.config.clj:247)
	at riemann.config$eval543$stream__1877.invoke(riemann.config.clj:247)
	at riemann.config$eval543$stream__4235$fn__4240.invoke(riemann.config.clj:194)
	at riemann.config$eval543$stream__4235.invoke(riemann.config.clj:194)
	at riemann.config$eval543$stream__4278$fn__4283.invoke(riemann.config.clj:120)
	at riemann.config$eval543$stream__4278.invoke(riemann.config.clj:120)
	at synygy.riemann.core$infer_org$fn__51$fn__63.invoke(core.clj:29)
	at synygy.riemann.core$infer_org$fn__51.invoke(core.clj:29)
	at riemann.core$stream_BANG_$fn__4415.invoke(core.clj:19)
	at riemann.core$stream_BANG_.invoke(core.clj:18)
	at riemann.transport$handle.invoke(transport.clj:162)
	at riemann.transport.tcp$tcp_handler.invoke(tcp.clj:92)
	at riemann.transport.tcp$gen_tcp_handler$fn__4640.invoke(tcp.clj:65)
	at riemann.transport.tcp.proxy$io.netty.channel.ChannelInboundHandlerAdapter$ff19274a.channelRead(Unknown Source)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
	at io.netty.channel.AbstractChannelHandlerContext.access$700(AbstractChannelHandlerContext.java:32)
	at io.netty.channel.AbstractChannelHandlerContext$8.run(AbstractChannelHandlerContext.java:324)
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:36)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:722)
`

Would something similar to what's described here : https://github.com/riemann/riemann/issues/629 help in the increase of the pool size? Or could this be a configuration issue?

We are running  riemann-0.2.8-1.noarch
java version "1.7.0_21"
Java(TM) SE Runtime Environment (build 1.7.0_21-b11)
Java HotSpot(TM) 64-Bit Server VM (build 23.21-b01, mixed mode)

And a picture of the streams rate/second

![streams-rate](https://cloud.githubusercontent.com/assets/11157105/13045513/5cdcdab8-d3dc-11e5-82f0-53d797a8f320.png)

Thanks!

**Comment by cristi-** [comment]
Hi,

 The problem was fixed with the increase of ":queue-size 1000" to ":queue-size 10000" . So this was a configuration problem.

**Comment by jamtur01** [comment]
Thanks for letting us know!
