### ISSUE TITLE
influxdb JSON write protocol has been deprecated

### ISSUE THREAD

**Issue by huahaiy** [riemann/riemann#669]
Riemann is no longer working with a stock installation of influxdb since influxdb version 0.11.0. For now, one can set "json-write-enabled = true" in the [http] section of influxdb.conf to make it work. But this option will be disabled after 0.12.0 according to https://github.com/influxdata/influxdb/pull/5512

WARN [2016-03-24 19:01:34,739] defaultEventExecutorGroup-2-4 - riemann.config - riemann.influxdb$influxdb_9$stream__10987@7001f1c0 threw
clojure.lang.ExceptionInfo: clj-http: status 400 {:orig-content-encoding "gzip", :trace-redirects ["http://localhost:8086/write"], :request-time 3, :status 400, :headers {"Connection" "close", "Content-Length" "76", "Date" "Thu, 24 Mar 2016 19:01:34 GMT", "X-Influxdb-Version" "0.11.0", "Request-Id" "d417caab-f1f2-11e5-8039-000000000000", "Content-Type" "application/json"}, :body "{\"error\":\"JSON write protocol has been deprecated\"}\n"}
        at clj_http.client$wrap_exceptions$fn__9677.invoke(client.clj:183)
        at clj_http.client$wrap_accept$fn__9829.invoke(client.clj:536)
        at clj_http.client$wrap_accept_encoding$fn__9835.invoke(client.clj:550)
        at clj_http.client$wrap_content_type$fn__9824.invoke(client.clj:525)
        at clj_http.client$wrap_form_params$fn__9906.invoke(client.clj:697)
        at clj_http.client$wrap_nested_params$fn__9923.invoke(client.clj:726)
        at clj_http.client$wrap_method$fn__9876.invoke(client.clj:641)
        at clj_http.cookies$wrap_cookies$fn__8113.invoke(cookies.clj:124)
        at clj_http.links$wrap_links$fn__8969.invoke(links.clj:51)
        at clj_http.client$wrap_unknown_host$fn__9932.invoke(client.clj:742)
        at clj_http.client$post.doInvoke(client.clj:857)
        at clojure.lang.RestFn.invoke(RestFn.java:423)
        at riemann.influxdb$influxdb_9$stream__10987.invoke(influxdb.clj:176)
        at riemann.config$eval190$stream__191$fn__196.invoke(riemann.config:30)
        at riemann.config$eval190$stream__191.invoke(riemann.config:30)
        at riemann.core$stream_BANG_$fn__5727.invoke(core.clj:19)
        at riemann.core$stream_BANG_.invoke(core.clj:18)
        at riemann.transport$handle.invoke(transport.clj:159)
        at riemann.transport.tcp$tcp_handler.invoke(tcp.clj:94)
        at riemann.transport.tcp$gen_tcp_handler$fn__5949.invoke(tcp.clj:65)
        at riemann.transport.tcp.proxy$io.netty.channel.ChannelInboundHandlerAdapter$ff19274a.channelRead(Unknown Source)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
        at io.netty.channel.AbstractChannelHandlerContext.access$700(AbstractChannelHandlerContext.java:32)
        at io.netty.channel.AbstractChannelHandlerContext$8.run(AbstractChannelHandlerContext.java:324)
        at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:36)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Thread.java:745)

**Comment by amir** [comment]
Line protocol support seems to be added in #575, but not released yet.

**Comment by furnacification** [comment]
influx 0.12 has now broken it completely.

**Comment by pradeepchhetri** [comment]
Influxdb is one of those softwares which loves pushing backward incompatible changes. Don't know why.

**Comment by faxm0dem** [comment]
/me taps himself on the back for moving away from influxdb

**Comment by pradeepchhetri** [comment]
@faxm0dem which time-series database you are using now ?

**Comment by faxm0dem** [comment]
Elasticsearch using [samplerr](/ccin2p3/samplerr)

**Comment by calston** [comment]
@aphyr We are dying without a new release...

**Comment by furnacification** [comment]
It's pretty easy to compile it from source until @aphyr does the official release. 

But be warned, grafana needs to move to v3 to work with influx 12. v3 is still in beta.

**Comment by jamtur01** [comment]
There's a new release out.
