### ISSUE TITLE
[question/help] multiple async-queues

### ISSUE THREAD

**Issue by jeekajoo** [riemann/riemann#720]
Hi,

I would like to be able to send events to influxdb AND to an upstream riemann server.
I tried both independently with success. But I can't seem to get both running at the same time:
```
riemann                | ERROR [2016-09-15 14:33:47,777] main - riemann.bin - Couldn't start
riemann                | clojure.lang.Compiler$CompilerException: java.lang.IllegalArgumentException: won't conj service: #object[riemann.service.ExecutorServiceService 0x60816371 "riemann.service.ExecutorServiceService@60816371"] would conflict with (#object[riemann.service.ExecutorServiceService 0x678586f0 "riemann.service.ExecutorServiceService@678586f0"]), compiling:(/etc/riemann/riemann.config:104:1)
riemann                | 	at clojure.lang.Compiler.load(Compiler.java:7391)
riemann                | 	at clojure.lang.Compiler.loadFile(Compiler.java:7317)
riemann                | 	at clojure.lang.RT$3.invoke(RT.java:320)
riemann                | 	at riemann.config$include.invokeStatic(config.clj:406)
riemann                | 	at riemann.config$include.invoke(config.clj:384)
riemann                | 	at riemann.bin$_main.invokeStatic(bin.clj:99)
riemann                | 	at riemann.bin$_main.invoke(bin.clj:85)
riemann                | 	at clojure.lang.AFn.applyToHelper(AFn.java:156)
riemann                | 	at clojure.lang.AFn.applyTo(AFn.java:144)
riemann                | 	at riemann.bin.main(Unknown Source)
riemann                | Caused by: java.lang.IllegalArgumentException: won't conj service: #object[riemann.service.ExecutorServiceService 0x60816371 "riemann.service.ExecutorServiceService@60816371"] would conflict with (#object[riemann.service.ExecutorServiceService 0x678586f0 "riemann.service.ExecutorServiceService@678586f0"])
riemann                | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
riemann                | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
riemann                | 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
riemann                | 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
riemann                | 	at clojure.lang.Reflector.invokeConstructor(Reflector.java:180)
riemann                | 	at riemann.core$conj_service.invokeStatic(core.clj:98)
riemann                | 	at riemann.core$conj_service.invoke(core.clj:81)
riemann                | 	at riemann.core$conj_service.invokeStatic(core.clj:84)
riemann                | 	at riemann.core$conj_service.invoke(core.clj:81)
riemann                | 	at clojure.lang.Atom.swap(Atom.java:51)
riemann                | 	at clojure.core$swap_BANG_.invokeStatic(core.clj:2261)
riemann                | 	at clojure.core$swap_BANG_.invoke(core.clj:2253)
riemann                | 	at riemann.config$service_BANG_.invokeStatic(config.clj:114)
riemann                | 	at riemann.config$service_BANG_.invoke(config.clj:81)
riemann                | 	at riemann.config$async_queue_BANG_.invokeStatic(config.clj:260)
riemann                | 	at riemann.config$async_queue_BANG_.doInvoke(config.clj:232)
riemann                | 	at clojure.lang.RestFn.invoke(RestFn.java:442)
riemann                | 	at riemann.config$eval338.invokeStatic(riemann.config:112)
riemann                | 	at riemann.config$eval338.invoke(riemann.config:104)
riemann                | 	at clojure.lang.Compiler.eval(Compiler.java:6927)
riemann                | 	at clojure.lang.Compiler.load(Compiler.java:7379)
riemann                | 	... 9 common frames omitted
```

```clojure
(let [index (index)
      downstream (batch 100 1/10
        (async-queue! :agg { :queue-size     1e3
                             :core-pool-size 4
                             :max-pool-size  32}
          (forward
            (riemann.client/tcp-client :host "riemann-master"))))
      influxBatchSender (batch 100 1/10
        (async-queue! :agg {:queue-size 1000
                                   :core-pool-size 1
                                   :max-pool-size 4
                                   :keep-alive-time 60000}
                             (influxdb influxdb-creds)))]
  (streams
    (default :ttl 150
      index
      ;influxBatchSender
      (where (service #"^riemann.*")
        downstream
      ))))
```

Am I missing something? Can we run multiple async-queues?
Thank you.

J.

**Comment by faxm0dem** [comment]
The first argument to `async-queue!` is the name of the queue.
If you want two then give them different names!

**Comment by jeekajoo** [comment]
oh, well :)
thank you! closing.
