### ISSUE TITLE
How to keep Graphite format in Riemann kafka output

### ISSUE THREAD

**Issue by keyboardfann** [riemann/riemann#818]
Dear All,
    I want to use push metrics use this way  source -> telegraf1 -> riemann -> kafka -> telegraf2 -> graphite,  but riemann kafka output use json-serialize and transform graphite format to JSON format. How do I keep  graphite format but not JSON format to kafka?

riemann.config
```
(logging/init {:file "/var/log/riemann/riemann.log"})

(let [host "0.0.0.0"]
  (udp-server {:host host})
  (ws-server  {:host host}))

(periodically-expire 5)
(def kafka-output (kafka {:bootstrap.servers "xxx:9092"
		          :acks 0}))
(streams
  (kafka-output "test1"))
```

telegraf1 output:
```
<metrics name, metrics type , value  timestamp>
1659157,metric_type=counter value=2i 1495175700000000000
2717853,metric_type=counter value=8i 1495175700000000000
2832858,metric_type=counter value=5i 1495175700000000000
640877,metric_type=counter value=7i 1495175700000000000
2015872,metric_type=counter value=5i 1495175700000000000
1819582,metric_type=counter value=1i 1495175700000000000
```

kafka output
```
{"host":"tng1400","service":"1545454/value","state":null,"description":null,"metric":4,"tags":["counter"],"time":1495175220,"ttl":null,"metric_type":"counter"}
{"host":"tng1400","service":"2247789/value","state":null,"description":null,"metric":5,"tags":["counter"],"time":1495175220,"ttl":null,"metric_type":"counter"}
{"host":"tng1400","service":"2408155/value","state":null,"description":null,"metric":7,"tags":["counter"],"time":1495175220,"ttl":null,"metric_type":"counter"}
{"host":"tng1400","service":"491214/value","state":null,"description":null,"metric":8,"tags":["counter"],"time":1495175220,"ttl":null,"metric_type":"counter"}
{"host":"tng1400","service":"655585/value","state":null,"description":null,"metric":4,"tags":["counter"],"time":1495175220,"ttl":null,"metric_type":"counter"}
```

**Comment by mcorbin** [comment]
Hi,

If i remember correctly, Telegraf sends events to Riemann using the Riemann protocol, so the telegraf1 graphite output is converted into a Riemann event.

Regarding Kafka, You should write your own Kafka serializer. The Kafka output uses [kinsky](https://github.com/pyr/kinsky), so you can do something like :

```
(require
  '[kinsky.client :as client]

(defn graphite-serializer
  []
  (client/serializer
    (fn [_ payload] (some-> payload converts-to-graphite .getBytes))))

(def kafka-output (kafka {:bootstrap.servers "xxx:9092"
                          :key.serializer client/string-serializer
                          :value.serializer graphite-serializer
		          :acks 0}))
```

Where converts-to-graphite is a function accepting an event and returning a graphite string.

**Comment by keyboardfann** [comment]
Dear @mcorbin,
   Thank you for quickly reply. If I change telegraf2 to Riemainn kafka input and output to Graphite plugin, is it easier than write the serializer ?

Fann

**Comment by keyboardfann** [comment]
Dear @mcorbin,
   I am not familiar with Clojure language. when I try to write kafka consumer config, it has an exception. Do I have something wrong?

Riemann.config
```
(logging/init {:file "/var/log/riemann/riemann.log"})

(let [host "0.0.0.0"]
  (tcp-server {:host host})
  (udp-server {:host host})
  (ws-server  {:host host}))

(periodically-expire 5)


(def kafka-import (kafka-consumer {:consumer.config {:bootstrap.servers "tng1398:9092"
				   :group.id "riemann"                  
				  }:topic "test1"   }))

(streams (kafka-import) )

```
Riemann.log
```
ERROR [2017-05-19 19:01:30,167] main - riemann.bin - Couldn't start
clojure.lang.Compiler$CompilerException: java.lang.ClassCastException: riemann.kafka$kafka_consumer$reify__9807 cannot be cast to clojure.lang.IFn, compiling:(/etc/riemann/riemann.config:31:1)
        at clojure.lang.Compiler.load(Compiler.java:7391)
        at clojure.lang.Compiler.loadFile(Compiler.java:7317)
        at clojure.lang.RT$3.invoke(RT.java:320)
        at riemann.config$include.invokeStatic(config.clj:440)
        at riemann.config$include.invoke(config.clj:418)
        at riemann.bin$_main.invokeStatic(bin.clj:99)
        at riemann.bin$_main.doInvoke(bin.clj:85)
        at clojure.lang.RestFn.invoke(RestFn.java:425)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at riemann.bin.main(Unknown Source)
Caused by: java.lang.ClassCastException: riemann.kafka$kafka_consumer$reify__9807 cannot be cast to clojure.lang.IFn
        at riemann.config$eval30.invokeStatic(riemann.config:31)
        at riemann.config$eval30.invoke(riemann.config:31)
        at clojure.lang.Compiler.eval(Compiler.java:6927)
        at clojure.lang.Compiler.load(Compiler.java:7379)
        ... 10 common frames omitted
```

**Comment by mcorbin** [comment]
>  Thank you for quickly reply. If I change telegraf2 to Riemainn kafka input and output to Graphite , is it easier than write the serializer ?

I don't understand, you want  source -> telegraf1 -> riemann -> kafka -> telegraf2 -> riemann -> graphite ? 

If yes, writing a serializer is easier (i can write the fn for you tonight). You can also do telegraf1 -> riemann -> graphite, or telegraf1 -> riemann -> (kafka AND graphite).

If you want to consume kafka, just add:

```clojure

(kafka-consumer {:consumer.config {:bootstrap.servers "localhost:9092"
                                                             :group.id "riemann"}
                               :topics ["test1"]})

```

In your config and it should work (no need to define a var).

**Comment by keyboardfann** [comment]
Dear @mcorbin,
    Originally I want this flow: source -> telegraf1 -> riemann -> kafka -> telegraf2 -> graphite, but it should write kafka serialize and I am not very familiar with cloujure, if you can help, I appreciate your kindness.
If you don't have time , I want to try source -> telegraf1 -> riemann kafka producer -> kafka -> riemann kafka consumer-> graphite, I think this flow also can solve my problem.

   Another question, I change the comsumer setting and consumer can connect to kafka. I also push some message to kafka but I can't find consumer start consume. How do I print the consume message for debug?

riemann.log 
```
[root@xx ~]# tailf /var/log/riemann/riemann.log 
INFO [2017-05-19 23:42:30,460] clojure-agent-send-off-pool-4 - riemann.transport.websockets - Websockets server 0.0.0.0 5556 online
INFO [2017-05-19 23:42:30,485] clojure-agent-send-off-pool-3 - org.apache.kafka.common.utils.AppInfoParser - Kafka version : 0.10.0.1
INFO [2017-05-19 23:42:30,489] clojure-agent-send-off-pool-3 - org.apache.kafka.common.utils.AppInfoParser - Kafka commitId : a7a17cdec9eaa6c5
INFO [2017-05-19 23:42:30,495] clojure-agent-send-off-pool-0 - riemann.kafka - Subscribing to  (riemann) ...
INFO [2017-05-19 23:42:30,608] clojure-agent-send-off-pool-2 - riemann.transport.udp - UDP server 0.0.0.0 5555 16384 -1 online
INFO [2017-05-19 23:42:30,627] clojure-agent-send-off-pool-3 - riemann.transport.tcp - TCP server 0.0.0.0 5555 online
INFO [2017-05-19 23:42:30,629] main - riemann.core - Hyperspace core online
INFO [2017-05-19 23:42:30,662] clojure-agent-send-off-pool-0 - org.apache.kafka.clients.consumer.internals.AbstractCoordinator - Discovered coordinator xxx:9092 (id: 2147483647 rack: null) for group riemann.
INFO [2017-05-19 23:42:30,664] clojure-agent-send-off-pool-0 - org.apache.kafka.clients.consumer.internals.ConsumerCoordinator - Revoking previously assigned partitions [] for group riemann
INFO [2017-05-19 23:42:30,664] clojure-agent-send-off-pool-0 - org.apache.kafka.clients.consumer.internals.AbstractCoordinator - (Re-)joining group riemann
INFO [2017-05-19 23:42:53,859] clojure-agent-send-off-pool-0 - org.apache.kafka.clients.consumer.internals.AbstractCoordinator - Successfully joined group riemann with generation 15
INFO [2017-05-19 23:42:53,860] clojure-agent-send-off-pool-0 - org.apache.kafka.clients.consumer.internals.ConsumerCoordinator - Setting newly assigned partitions [riemann-2, riemann-0, riemann-1] for group riemann

```

**Comment by mcorbin** [comment]
Riemann provides a [Graphite output](http://riemann.io/howto.html#forward-to-graphite). So you can do :

```clojure
(streams
  (graphite {:host "localhost"})
  (kafka-output "test1"))
```
to send Riemann events to Graphite and Kafka.

If you want to send events only to Kafka, here is the converts-to-graphite fn :

```clojure
(defn converts-to-graphite
  [event]
  (str (clojure.string/join " " [(riemann.graphite/graphite-path-percentiles event)
                                 (riemann.graphite/graphite-metric event)
                                 (int (:time event))])))
```

Example using the REPL:

```clojure
(converts-to-graphite {:host "tng1400" :service "655585/value" :state nil :description nil :metric 4 :tags ["counter"] :time 1495175220 :ttl nil :metric_type "counter"})
"tng1400.655585/value 4 1495175220"
```

> Another question, I change the comsumer setting and consumer can connect to kafka. I also push some message to kafka but I can't find consumer start consume. How do I print the consume message for debug?

Just do :

```clojure
(streams
  #(info %))
```

In Riemann, a stream can have multiple children. If you want to debug events and send them to Kafka, you can do :

```clojure
(streams
  (kafka-output "test1")
  #(info %))
```

**Comment by keyboardfann** [comment]
Dear @mcorbin ,
    Thank you for the information, I will try it and give you feedback later. 

Fann

**Comment by keyboardfann** [comment]
Dear  @mcorbin,
    I test the function and works good, but I still have some questions. Sorry for so many question.
    Because I use telegraf statsd input plugin, so I also want to keep the statsd format. So I write a graphite-path-test function , but how I can replace the tag value counter to stats_counts?
    After I write the function and put them to riemann.conf, I restart riemann service but show error(Wrong number of args (0) passed) in the log, line 99 is the converts-to-graphite function,  how could I solve the problem?

Lein
```
riemann.graphite=> (defn graphite-path-test
              #_=>   "Constructs a path for an event. Takes the hostname fqdn, reversed,
              #_=>   followed by the service, with spaces converted to dots."
              #_=>   [event]
              #_=>   (let [service (:service event)
              #_=> tags (:tags event)
              #_=>         split-service (if service (split service #"/") [])
              #_=> 
              #_=>         ]
              #_=>      (join "." (concat (reverse tags) split-service))))
#'riemann.graphite/graphite-path-test
riemann.graphite=> 

riemann.graphite=> (defn converts-to-graphite
              #_=>   [event]
              #_=>   (str (clojure.string/join " " [(riemann.graphite/graphite-path-test event)
              #_=>                                  (riemann.graphite/graphite-metric event)
              #_=>                                  (int (:time event))])
              #_=>        "\n"))
#'riemann.graphite/converts-to-graphite
riemann.graphite=> 

riemann.graphite=>  (converts-to-graphite {:host "tng1400" :service "655585/value" :state nil :description nil :metric 4 :tags ["counter"] :time 1495175220 :ttl nil :metric_type "counter"})
"counter.655585.value 4 1495175220\n"
```

Riemann config
```
(logging/init {:file "/var/log/riemann/riemann.log"})

(let [host "0.0.0.0"]
  (udp-server {:host host})
  (ws-server  {:host host}))

(periodically-expire 5)


(defn graphite-path-test
  "Constructs a path for an event. Takes the hostname fqdn, reversed,
  followed by the service, with spaces converted to dots."
  [event]
  (let [service (:service event)
		tags (:tags event)
        split-service (if service (split service #"/") [])
        ]
     (clojure.string/join "." (concat (reverse tags) split-service))))
	 
	 
	 
(defn converts-to-graphite
  [event]
  (str (clojure.string/join " " [(graphite-path-test event)
                                 (riemann.graphite/graphite-metric event)
                                 (int (:time event))])
       "\n"))


(def kafka-output (kafka {:bootstrap.servers "tng1398:9092" 
                          :value.serializer converts-to-graphite }))
(streams
  (kafka-output "test1"))

```


riemann.log
```
ERROR [2017-05-22 11:38:42,229] main - riemann.bin - Couldn't start
clojure.lang.Compiler$CompilerException: clojure.lang.ArityException: Wrong number of args (0) passed to: config/converts-to-graphite, compiling:(riemann.config:99:19)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3657)
	at clojure.lang.Compiler$DefExpr.eval(Compiler.java:451)
	at clojure.lang.Compiler.eval(Compiler.java:6932)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	at clojure.lang.Compiler.loadFile(Compiler.java:7317)
	at clojure.lang.RT$3.invoke(RT.java:320)
	at riemann.config$include.invokeStatic(config.clj:440)
	at riemann.config$include.invoke(config.clj:418)
	at riemann.bin$_main.invokeStatic(bin.clj:99)
	at riemann.bin$_main.doInvoke(bin.clj:85)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at riemann.bin.main(Unknown Source)
Caused by: clojure.lang.ArityException: Wrong number of args (0) passed to: config/converts-to-graphite
	at clojure.lang.AFn.throwArity(AFn.java:429)
	at clojure.lang.AFn.invoke(AFn.java:28)
	at kinsky.client$__GT_serializer.invokeStatic(client.clj:215)
	at kinsky.client$__GT_serializer.invoke(client.clj:209)
	at kinsky.client$producer.invokeStatic(client.clj:487)
	at kinsky.client$producer.invoke(client.clj:478)
	at riemann.kafka$kafka.invokeStatic(kafka.clj:37)
	at riemann.kafka$kafka.invoke(kafka.clj:10)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3652)
	... 13 common frames omitted

```

**Comment by mcorbin** [comment]
Hi,

I see several issues in your code:

```
riemann.graphite=>  (converts-to-graphite {:host "tng1400" :service "655585/value" :state nil :description nil :metric 4 :tags ["counter"] :time 1495175220 :ttl nil :metric_type "counter"})
"[.\".s.t.a.t.s._.c.o.u.n.t.s.\".].655585.value 4 1495175220\n"
```
The string  **[.\".s.t.a.t.s._.c.o.u.n.t.s.\".].655585.value 4 1495175220\n** is incorrect. You probably want "stats.counts.655585.value 4 1495175220\n".

Here is a simpler graphite-path-test fn :

```clojure
(defn graphite-path-test
  "Constructs a path for an event. Takes the hostname fqdn, reversed,
              followed by the service, with spaces converted to dots."
  [event]
  (let [;; replace all "/" by "." in service
        service (clojure.string/replace (:service event) #"/" ".")
        ;; returns the statd metric type using :metric_type value
        metric-type (condp = (:metric_type event)
                      "counter" "stats_counts")]
    (str metric-type "." service)))

;; examples using the repl :
(graphite-path-test {:host "tng1400" :service "655585/value" :state nil :description nil :metric 4 :tags ["counter"] :time 1495175220 :ttl nil :metric_type "counter"})
"stats_counts.655585.value"

(converts-to-graphite {:host "tng1400" :service "655585/value" :state nil :description nil :metric 4 :tags ["counter"] :time 1495175220 :ttl nil :metric_type "counter"})
"stats_counts.655585.value 4 1495175220\n"
```

I don't understand why you used :tags instead of :metric_type to get the metric type. Using condp, you can add other metric types if needed.

Second problem :

```
Caused by: clojure.lang.ArityException: Wrong number of args (0) passed to: config/converts-to-graphite
```

I think It's because you should use a serializer like in my first example is this issue and not use  converts-to-graphite directly:

```clojure
(defn graphite-serializer
  []
  (client/serializer
    (fn [_ payload] (some-> payload converts-to-graphite .getBytes))))
```

**Comment by keyboardfann** [comment]
Dear @mcorbin ,
    I can follow your step to get the right result now. But when I put all to riemann.config and start riemann , it displays "No such namespace: client ". So I change namespace to kafka, it can find client namespace but show another error "Unable to resolve symbol: streams in this context" happened.

```
riemann.graphite=> (defn graphite-path-test
              #_=>   "Constructs a path for an event. Takes the hostname fqdn, reversed,
              #_=>               followed by the service, with spaces converted to dots."
              #_=>   [event]
              #_=>   (let [;; replace all "/" by "." in service
              #_=>         service (clojure.string/replace (:service event) #"/value" "")
              #_=>         ;; returns the statd metric type using :metric_type value
              #_=>         metric-type (condp = (:metric_type event)
              #_=>                       "counter" "stats_counts"
              #_=>   "gagues" "stats.gagues")]
              #_=> 
              #_=>     (str metric-type "." service)))
#'riemann.graphite/graphite-path-test

riemann.graphite=> (defn converts-to-graphite
              #_=>   [event]
              #_=>   (str (clojure.string/join " " [(graphite-path-test event)
              #_=>                                  (riemann.graphite/graphite-metric event)
              #_=>                                  (int (:time event))])
              #_=>        "\n"))
#'riemann.graphite/converts-to-graphite
riemann.graphite=> 


riemann.graphite=> (converts-to-graphite {:host "tng1400" :service "655585/value" :state nil :description nil :metric 4 :tags ["counter"] :time 1495175220 :ttl nil :metric_type "counter"})
"stats_counts.655585 4 1495175220\n"
```

```
(logging/init {:file "/var/log/riemann/riemann.log"})

(let [host "0.0.0.0"]
  (udp-server {:host host})
  (ws-server  {:host host}))

(periodically-expire 5)


(defn graphite-path-test
  "Constructs a path for an event. Takes the hostname fqdn, reversed,
              followed by the service, with spaces converted to dots."
  [event]
        service (clojure.string/replace (:service event) #"/value" "")
        metric-type (condp = (:metric_type event)
                      "counter" "stats_counts"
					  "gagues" "stats.gagues")]

    (str metric-type "." service)))
	
	
(defn converts-to-graphite
  [event]
  (str (clojure.string/join " " [(graphite-path-test event)
                                 (riemann.graphite/graphite-metric event)
                                 (int (:time event))])
       "\n"))


(defn graphite-serializer
  []
  (client/serializer
    (fn [_ payload] (some-> payload converts-to-graphite .getBytes))))

(def kafka-output (kafka {:bootstrap.servers "tng1398:9092"
                          :key.serializer  client/string-serializer
                          :value.serializer graphite-serializer
                         }))
(streams
  (kafka-output "test1"))
```

riemann.config
```
...
...
...
(defn graphite-path-test
  "Constructs a path for an event. Takes the hostname fqdn, reversed,
              followed by the service, with spaces converted to dots."
  [event]
        service (clojure.string/replace (:service event) #"/value" "")
        metric-type (condp = (:metric_type event)
                      "counter" "stats_counts"
					  "gagues" "stats.gagues")]

    (str metric-type "." service)))
	
	
(defn converts-to-graphite
  [event]
  (str (clojure.string/join " " [(graphite-path-test event)
                                 (riemann.graphite/graphite-metric event)
                                 (int (:time event))])
       "\n"))


(defn graphite-serializer
  []
  (client/serializer
    (fn [_ payload] (some-> payload converts-to-graphite .getBytes))))

(def kafka-output (kafka {:bootstrap.servers "tng1398:9092"
                          :key.serializer  client/string-serializer
                          :value.serializer graphite-serializer
                         }))
(streams
  (kafka-output "test1"))

```

riemann.log
```
ERROR [2017-05-23 01:00:22,099] main - riemann.bin - Couldn't start
clojure.lang.Compiler$CompilerException: java.lang.RuntimeException: No such namespace: client, compiling:(/etc/riemann/riemann.config:99:3)
        at clojure.lang.Compiler.analyze(Compiler.java:6688)

```

riemann.config ADD
```
(ns riemann.kafka
  "Receives events from and forwards events to Kafka."
  (:require [kinsky.client :as client]
            [cheshire.core :as json])
  (:use [riemann.common        :only [event]]
        [riemann.core          :only [stream!]]
        [riemann.service       :only [Service ServiceEquiv]]
        [clojure.tools.logging :only [info error]]))
...
...
...
```

```
INFO [2017-05-23 01:15:20,619] main - org.apache.kafka.clients.producer.ProducerConfig - ProducerConfig values: 
	metric.reporters = []
	metadata.max.age.ms = 300000
	reconnect.backoff.ms = 50
	sasl.kerberos.ticket.renew.window.factor = 0.8
	bootstrap.servers = [xxx:9092]
	ssl.keystore.type = JKS
	sasl.mechanism = GSSAPI
	max.block.ms = 60000
	interceptor.classes = null
	ssl.truststore.password = null
	client.id = producer-1
	ssl.endpoint.identification.algorithm = null
	request.timeout.ms = 30000
	acks = 1
	receive.buffer.bytes = 32768
	ssl.truststore.type = JKS
	retries = 0
	ssl.truststore.location = null
	ssl.keystore.password = null
	send.buffer.bytes = 131072
	compression.type = none
	metadata.fetch.timeout.ms = 60000
	retry.backoff.ms = 100
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	buffer.memory = 33554432
	timeout.ms = 30000
	key.serializer = class kinsky.client$serializer$reify__9622
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	ssl.trustmanager.algorithm = PKIX
	block.on.buffer.full = false
	ssl.key.password = null
	sasl.kerberos.min.time.before.relogin = 60000
	connections.max.idle.ms = 540000
	max.in.flight.requests.per.connection = 5
	metrics.num.samples = 2
	ssl.protocol = TLS
	ssl.provider = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
	batch.size = 16384
	ssl.keystore.location = null
	ssl.cipher.suites = null
	security.protocol = PLAINTEXT
	max.request.size = 1048576
	value.serializer = class kinsky.client$serializer$reify__9622
	ssl.keymanager.algorithm = SunX509
	metrics.sample.window.ms = 30000
	partitioner.class = class org.apache.kafka.clients.producer.internals.DefaultPartitioner
	linger.ms = 0

INFO [2017-05-23 01:15:20,620] main - org.apache.kafka.common.utils.AppInfoParser - Kafka version : 0.10.0.1
INFO [2017-05-23 01:15:20,621] main - org.apache.kafka.common.utils.AppInfoParser - Kafka commitId : a7a17cdec9eaa6c5
ERROR [2017-05-23 01:15:20,629] main - riemann.bin - Couldn't start
clojure.lang.Compiler$CompilerException: java.lang.RuntimeException: Unable to resolve symbol: streams in this context, compiling:(/etc/riemann/riemann.config:115:1)

```

**Comment by mcorbin** [comment]
in riemann.config, you should require kinsky:

```clojure
(require '[kinsky.client :as client])
```

**Comment by keyboardfann** [comment]
Dear @mcorbin ,
    Yes , require the package and can start , but show No matching clause , maybe the function have some problem .
```
INFO [2017-05-23 01:24:27,995] main - org.apache.kafka.common.utils.AppInfoParser - Kafka version : 0.10.0.1
INFO [2017-05-23 01:24:27,995] main - org.apache.kafka.common.utils.AppInfoParser - Kafka commitId : a7a17cdec9eaa6c5

INFO [2017-05-23 01:24:28,084] clojure-agent-send-off-pool-3 - riemann.transport.websockets - Websockets server 0.0.0.0 5556 online
INFO [2017-05-23 01:24:28,171] clojure-agent-send-off-pool-0 - riemann.transport.udp - UDP server 0.0.0.0 5555 16384 -1 online
INFO [2017-05-23 01:24:28,173] main - riemann.core - Hyperspace core online
WARN [2017-05-23 01:24:38,104] Thread-6 - riemann.core - instrumentation service caught
java.lang.IllegalArgumentException: No matching clause: 
	at riemann.config$graphite_path_test.invokeStatic(riemann.config:84)
	at riemann.config$graphite_path_test.invoke(riemann.config:77)
	at riemann.config$converts_to_graphite.invokeStatic(riemann.config:93)
	at riemann.config$converts_to_graphite.invoke(riemann.config:91)
	at riemann.config$graphite_serializer$fn__36.invoke(riemann.config:102)
	at kinsky.client$serializer$reify__9622.serialize(client.clj:127)
	at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:453)
	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:430)
	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:353)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
	at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
	at kinsky.client$producer$reify__9765.send_BANG_(client.clj:468)
	at riemann.kafka$kafka$make_stream__9772$stream__9773.invoke(kafka.clj:42)
	at riemann.core$stream_BANG_$fn__8578.invoke(core.clj:19)
	at riemann.core$stream_BANG_.invokeStatic(core.clj:18)
	at riemann.core$stream_BANG_.invoke(core.clj:14)
	at riemann.core$instrumentation_service$measure__8587.invoke(core.clj:57)
	at riemann.service.ThreadService$thread_service_runner__6217$fn__6218.invoke(service.clj:71)
	at riemann.service.ThreadService$thread_service_runner__6217.invoke(service.clj:70)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.lang.Thread.run(Thread.java:748)
```

```
 77 (defn graphite-path-test
 78   "Constructs a path for an event. Takes the hostname fqdn, reversed,
 79               followed by the service, with spaces converted to dots."
 80   [event]
 81   (let [;; replace all "/" by "." in service
 82         service (clojure.string/replace (:service event) #"/value" "")
 83         ;; returns the statd metric type using :metric_type value
 84         metric-type (condp = (:metric_type event)
 85                       "counter" "stats_counts"
 86                 )]

```

**Comment by keyboardfann** [comment]
Seems riemann system metrics format can't transform to graphite format, so the function show exception.

```
INFO [2017-05-23 01:38:21,193] Thread-8 - riemann.config - #riemann.codec.Event{:host tng1397, :service riemann streams rate, :state nil, :description nil, :metric 0.0, :tags [riemann], :time 373868675293/250, :ttl 20}
WARN [2017-05-23 01:38:21,238] Thread-8 - riemann.core - instrumentation service caught
java.lang.IllegalArgumentException: No matching clause: 
	at riemann.config$graphite_path_test.invokeStatic(riemann.config:84)
	at riemann.config$graphite_path_test.invoke(riemann.config:77)
	at riemann.config$converts_to_graphite.invokeStatic(riemann.config:93)
	at riemann.config$converts_to_graphite.invoke(riemann.config:91)
	at riemann.config$graphite_serializer$fn__36.invoke(riemann.config:102)
	at kinsky.client$serializer$reify__9622.serialize(client.clj:127)
	at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:453)
	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:430)
	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:353)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
	at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
	at kinsky.client$producer$reify__9765.send_BANG_(client.clj:468)
	at riemann.kafka$kafka$make_stream__9772$stream__9773.invoke(kafka.clj:42)
	at riemann.core$stream_BANG_$fn__8578.invoke(core.clj:19)
	at riemann.core$stream_BANG_.invokeStatic(core.clj:18)
	at riemann.core$stream_BANG_.invoke(core.clj:14)
	at riemann.core$instrumentation_service$measure__8587.invoke(core.clj:57)
	at riemann.service.ThreadService$thread_service_runner__6217$fn__6218.invoke(service.clj:71)
	at riemann.service.ThreadService$thread_service_runner__6217.invoke(service.clj:70)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by mcorbin** [comment]
Yes, it's because i used "condp" to get the statsd format.

You can for example filter the riemann internal events using (where) in streams :

```
(where (not (service #"^riemann "))
  ...)

**Comment by keyboardfann** [comment]
Dear @mcorbin,
    It's big thanks to helping so many questions, the following config can help me keep statsd metrics format to kafka, and transfer riemann system to graphite directly.

Riemann config:
```
(require '[kinsky.client :as client])

(defn graphite-path-test
  "Constructs a path for an event. Takes the hostname fqdn, reversed,
              followed by the service, with spaces converted to dots."
  [event]
  (let [;; replace all "/" by "." in service
        service (clojure.string/replace (:service event) #"/value" "")
        ;; returns the statd metric type using :metric_type value
        metric-type (condp = (:metric_type event)
                      "counter" "stats_counts"
                      "gauge"  "stats.gauges"
		)]
    (str metric-type "." service)))
	
	
(defn converts-to-graphite
  [event]
  (str (clojure.string/join " " [(graphite-path-test event)
                                 (riemann.graphite/graphite-metric event)
                                 (int (:time event))])
       "\n"))


(defn graphite-serializer
  []
  (client/serializer
    (fn [_ payload] (some-> payload converts-to-graphite .getBytes))))

(def kafka-output (kafka {:bootstrap.servers "aaa:9092"
                          :key.serializer  client/string-serializer
                          :value.serializer graphite-serializer
                         }))

(streams
(where (not (service #"^riemann "))
  (kafka-output "test1"))
  (graphite {:host "bbb"})
)
```

**Comment by mcorbin** [comment]
You're welcome ;) Do not hesitate if you have other questions. If it's OK for you, can you close the issue ?
