### ISSUE TITLE
Error using clojure 1.9 / campfire integration

### ISSUE THREAD

**Issue by mcorbin** [riemann/riemann#866]
Using Clojure 1.9, i have this error when i try to run the Riemann project:

```clojure
Exception in thread "main" clojure.lang.ExceptionInfo: Call to clojure.core/defn did not conform to spec:
In: [2 0] val: {:keys [type user password realm preemptive], :or {:type :basic}} fails spec: :clojure.core.specs.alpha/arg-list at: [:args :bs :arity-n :bodies :args] predicate: vector?
In: [2 0] val: ({:keys [type user password realm preemptive], :or {:type :basic}} b) fails spec: :clojure.core.specs.alpha/arg-list at: [:args :bs :arity-1 :args] predicate: (cat :args (* :clojure.core.specs.alpha/binding-form) :varargs (? (cat :amp #{(quote &)} :form :clojure.core.specs.alpha/binding-form))),  Extra input
 #:clojure.spec.alpha{:problems ({:path [:args :bs :arity-1 :args], :reason "Extra input", :pred (clojure.spec.alpha/cat :args (clojure.spec.alpha/* :clojure.core.specs.alpha/binding-form) :varargs (clojure.spec.alpha/? (clojure.spec.alpha/cat :amp #{(quote &)} :form :clojure.core.specs.alpha/binding-form))), :val ({:keys [type user password realm preemptive], :or {:type :basic}} b), :via [:clojure.core.specs.alpha/defn-args :clojure.core.specs.alpha/args+body :clojure.core.specs.alpha/arg-list :clojure.core.specs.alpha/arg-list], :in [2 0]} {:path [:args :bs :arity-n :bodies :args], :pred clojure.core/vector?, :val {:keys [type user password realm preemptive], :or {:type :basic}}, :via [:clojure.core.specs.alpha/defn-args :clojure.core.specs.alpha/args+body :clojure.core.specs.alpha/args+body :clojure.core.specs.alpha/args+body :clojure.core.specs.alpha/arg-list :clojure.core.specs.alpha/arg-list], :in [2 0]}), :spec #object[clojure.spec.alpha$regex_spec_impl$reify__1188 0xfd8513b "clojure.spec.alpha$regex_spec_impl$reify__1188@fd8513b"], :value (set-realm "Sets realm on builder." [{:keys [type user password realm preemptive], :or {:type :basic}} b] (let [rbld (Realm$RealmBuilder.)] (.setScheme rbld (type->auth-scheme type)) (when (nil? user) (if (nil? password) (throw (IllegalArgumentException. "For authentication user and password is required")) (throw (IllegalArgumentException. "For authentication user is required")))) (when (nil? password) (throw (IllegalArgumentException. "For authentication password is required"))) (when (= :digest type) (when (nil? realm) (throw (IllegalArgumentException. "For DIGEST authentication realm is required"))) (.setRealmName rbld realm)) (when-not (nil? preemptive) (.setUsePreemptiveAuth rbld preemptive)) (doto rbld (.setPrincipal user) (.setPassword password)) (.setRealm b (.build rbld)))), :args (set-realm "Sets realm on builder." [{:keys [type user password realm preemptive], :or {:type :basic}} b] (let [rbld (Realm$RealmBuilder.)] (.setScheme rbld (type->auth-scheme type)) (when (nil? user) (if (nil? password) (throw (IllegalArgumentException. "For authentication user and password is required")) (throw (IllegalArgumentException. "For authentication user is required")))) (when (nil? password) (throw (IllegalArgumentException. "For authentication password is required"))) (when (= :digest type) (when (nil? realm) (throw (IllegalArgumentException. "For DIGEST authentication realm is required"))) (.setRealmName rbld realm)) (when-not (nil? preemptive) (.setUsePreemptiveAuth rbld preemptive)) (doto rbld (.setPrincipal user) (.setPassword password)) (.setRealm b (.build rbld))))}, compiling:(http/async/client/util.clj:46:1)
	at clojure.lang.Compiler.checkSpecs(Compiler.java:6891)
	at clojure.lang.Compiler.macroexpand1(Compiler.java:6907)
	at clojure.lang.Compiler.macroexpand(Compiler.java:6972)
	at clojure.lang.Compiler.eval(Compiler.java:7046)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	at clojure.lang.RT.loadResourceScript(RT.java:379)
	at clojure.lang.RT.loadResourceScript(RT.java:370)
	at clojure.lang.RT.load(RT.java:460)
	at clojure.lang.RT.load(RT.java:426)
	at clojure.core$load$fn__6550.invoke(core.clj:6051)
	at clojure.core$load.invokeStatic(core.clj:6050)
	at clojure.core$load.doInvoke(core.clj:6034)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5853)
	at clojure.core$load_one.invoke(core.clj:5848)
	at clojure.core$load_lib$fn__6495.invoke(core.clj:5893)
	at clojure.core$load_lib.invokeStatic(core.clj:5892)
	at clojure.core$load_lib.doInvoke(core.clj:5873)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$load_libs.invokeStatic(core.clj:5934)
	at clojure.core$load_libs.doInvoke(core.clj:5914)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:661)
	at clojure.core$use.invokeStatic(core.clj:6018)
	at clojure.core$use.doInvoke(core.clj:6018)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at http.async.client.request$eval10677$loading__6436__auto____10678.invoke(request.clj:15)
	at http.async.client.request$eval10677.invokeStatic(request.clj:15)
	at http.async.client.request$eval10677.invoke(request.clj:15)
	at clojure.lang.Compiler.eval(Compiler.java:7062)
	at clojure.lang.Compiler.eval(Compiler.java:7051)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	at clojure.lang.RT.loadResourceScript(RT.java:379)
	at clojure.lang.RT.loadResourceScript(RT.java:370)
	at clojure.lang.RT.load(RT.java:460)
	at clojure.lang.RT.load(RT.java:426)
	at clojure.core$load$fn__6550.invoke(core.clj:6051)
	at clojure.core$load.invokeStatic(core.clj:6050)
	at clojure.core$load.doInvoke(core.clj:6034)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5853)
	at clojure.core$load_one.invoke(core.clj:5848)
	at clojure.core$load_lib$fn__6495.invoke(core.clj:5893)
	at clojure.core$load_lib.invokeStatic(core.clj:5892)
	at clojure.core$load_lib.doInvoke(core.clj:5873)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$load_libs.invokeStatic(core.clj:5934)
	at clojure.core$load_libs.doInvoke(core.clj:5914)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:661)
	at clojure.core$use.invokeStatic(core.clj:6018)
	at clojure.core$use.doInvoke(core.clj:6018)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at http.async.client$eval10669$loading__6436__auto____10670.invoke(client.clj:17)
	at http.async.client$eval10669.invokeStatic(client.clj:17)
	at http.async.client$eval10669.invoke(client.clj:17)
	at clojure.lang.Compiler.eval(Compiler.java:7062)
	at clojure.lang.Compiler.eval(Compiler.java:7051)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	at clojure.lang.RT.loadResourceScript(RT.java:379)
	at clojure.lang.RT.loadResourceScript(RT.java:370)
	at clojure.lang.RT.load(RT.java:460)
	at clojure.lang.RT.load(RT.java:426)
	at clojure.core$load$fn__6550.invoke(core.clj:6051)
	at clojure.core$load.invokeStatic(core.clj:6050)
	at clojure.core$load.doInvoke(core.clj:6034)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5853)
	at clojure.core$load_one.invoke(core.clj:5848)
	at clojure.core$load_lib$fn__6495.invoke(core.clj:5893)
	at clojure.core$load_lib.invokeStatic(core.clj:5892)
	at clojure.core$load_lib.doInvoke(core.clj:5873)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$load_libs.invokeStatic(core.clj:5930)
	at clojure.core$load_libs.doInvoke(core.clj:5914)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$require.invokeStatic(core.clj:5952)
	at clojure.core$require.doInvoke(core.clj:5952)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clj_campfire.core$eval10602$loading__6436__auto____10603.invoke(core.clj:1)
	at clj_campfire.core$eval10602.invokeStatic(core.clj:1)
	at clj_campfire.core$eval10602.invoke(core.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7062)
	at clojure.lang.Compiler.eval(Compiler.java:7051)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	at clojure.lang.RT.loadResourceScript(RT.java:379)
	at clojure.lang.RT.loadResourceScript(RT.java:370)
	at clojure.lang.RT.load(RT.java:460)
	at clojure.lang.RT.load(RT.java:426)
	at clojure.core$load$fn__6550.invoke(core.clj:6051)
	at clojure.core$load.invokeStatic(core.clj:6050)
	at clojure.core$load.doInvoke(core.clj:6034)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5853)
	at clojure.core$load_one.invoke(core.clj:5848)
	at clojure.core$load_lib$fn__6495.invoke(core.clj:5893)
	at clojure.core$load_lib.invokeStatic(core.clj:5892)
	at clojure.core$load_lib.doInvoke(core.clj:5873)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$load_libs.invokeStatic(core.clj:5930)
	at clojure.core$load_libs.doInvoke(core.clj:5914)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$require.invokeStatic(core.clj:5952)
	at clojure.core$require.doInvoke(core.clj:5952)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at riemann.campfire$eval10596$loading__6436__auto____10597.invoke(campfire.clj:1)
	at riemann.campfire$eval10596.invokeStatic(campfire.clj:1)
	at riemann.campfire$eval10596.invoke(campfire.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7062)
	at clojure.lang.Compiler.eval(Compiler.java:7051)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	at clojure.lang.RT.loadResourceScript(RT.java:379)
	at clojure.lang.RT.loadResourceScript(RT.java:370)
	at clojure.lang.RT.load(RT.java:460)
	at clojure.lang.RT.load(RT.java:426)
	at clojure.core$load$fn__6550.invoke(core.clj:6051)
	at clojure.core$load.invokeStatic(core.clj:6050)
	at clojure.core$load.doInvoke(core.clj:6034)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5853)
	at clojure.core$load_one.invoke(core.clj:5848)
	at clojure.core$load_lib$fn__6495.invoke(core.clj:5893)
	at clojure.core$load_lib.invokeStatic(core.clj:5892)
	at clojure.core$load_lib.doInvoke(core.clj:5873)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$load_libs.invokeStatic(core.clj:5934)
	at clojure.core$load_libs.doInvoke(core.clj:5914)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$require.invokeStatic(core.clj:5952)
	at clojure.core$require.doInvoke(core.clj:5952)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at riemann.config$eval10556$loading__6436__auto____10557.invoke(config.clj:1)
	at riemann.config$eval10556.invokeStatic(config.clj:1)
	at riemann.config$eval10556.invoke(config.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7062)
	at clojure.lang.Compiler.eval(Compiler.java:7051)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	at clojure.lang.RT.loadResourceScript(RT.java:379)
	at clojure.lang.RT.loadResourceScript(RT.java:370)
	at clojure.lang.RT.load(RT.java:460)
	at clojure.lang.RT.load(RT.java:426)
	at clojure.core$load$fn__6550.invoke(core.clj:6051)
	at clojure.core$load.invokeStatic(core.clj:6050)
	at clojure.core$load.doInvoke(core.clj:6034)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5853)
	at clojure.core$load_one.invoke(core.clj:5848)
	at clojure.core$load_lib$fn__6495.invoke(core.clj:5893)
	at clojure.core$load_lib.invokeStatic(core.clj:5892)
	at clojure.core$load_lib.doInvoke(core.clj:5873)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$load_libs.invokeStatic(core.clj:5930)
	at clojure.core$load_libs.doInvoke(core.clj:5914)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$require.invokeStatic(core.clj:5952)
	at clojure.core$require.doInvoke(core.clj:5952)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at riemann.blueflood$eval374$loading__6436__auto____375.invoke(blueflood.clj:1)
	at riemann.blueflood$eval374.invokeStatic(blueflood.clj:1)
	at riemann.blueflood$eval374.invoke(blueflood.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7062)
	at clojure.lang.Compiler.eval(Compiler.java:7051)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	at clojure.lang.RT.loadResourceScript(RT.java:379)
	at clojure.lang.RT.loadResourceScript(RT.java:370)
	at clojure.lang.RT.load(RT.java:460)
	at clojure.lang.RT.load(RT.java:426)
	at clojure.core$load$fn__6550.invoke(core.clj:6051)
	at clojure.core$load.invokeStatic(core.clj:6050)
	at clojure.core$load.doInvoke(core.clj:6034)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5853)
	at clojure.core$load_one.invoke(core.clj:5848)
	at clojure.core$load_lib$fn__6495.invoke(core.clj:5893)
	at clojure.core$load_lib.invokeStatic(core.clj:5892)
	at clojure.core$load_lib.doInvoke(core.clj:5873)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$load_libs.invokeStatic(core.clj:5930)
	at clojure.core$load_libs.doInvoke(core.clj:5914)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:661)
	at clojure.core$use.invokeStatic(core.clj:6018)
	at clojure.core$use.doInvoke(core.clj:6018)
	at clojure.lang.RestFn.invoke(RestFn.java:551)
	at riemann.blueflood_test$eval366$loading__6436__auto____367.invoke(blueflood_test.clj:1)
	at riemann.blueflood_test$eval366.invokeStatic(blueflood_test.clj:1)
	at riemann.blueflood_test$eval366.invoke(blueflood_test.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7062)
	at clojure.lang.Compiler.eval(Compiler.java:7051)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	at clojure.lang.RT.loadResourceScript(RT.java:379)
	at clojure.lang.RT.loadResourceScript(RT.java:370)
	at clojure.lang.RT.load(RT.java:460)
	at clojure.lang.RT.load(RT.java:426)
	at clojure.core$load$fn__6550.invoke(core.clj:6051)
	at clojure.core$load.invokeStatic(core.clj:6050)
	at clojure.core$load.doInvoke(core.clj:6034)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5853)
	at clojure.core$load_one.invoke(core.clj:5848)
	at clojure.core$load_lib$fn__6495.invoke(core.clj:5893)
	at clojure.core$load_lib.invokeStatic(core.clj:5892)
	at clojure.core$load_lib.doInvoke(core.clj:5873)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$load_libs.invokeStatic(core.clj:5930)
	at clojure.core$load_libs.doInvoke(core.clj:5914)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$require.invokeStatic(core.clj:5952)
	at clojure.core$require.doInvoke(core.clj:5952)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:659)
	at clojure.core$apply.invoke(core.clj:652)
	at user$eval233.invokeStatic(form-init5165317835365868763.clj:1)
	at user$eval233.invoke(form-init5165317835365868763.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7062)
	at clojure.lang.Compiler.eval(Compiler.java:7052)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	at clojure.lang.Compiler.loadFile(Compiler.java:7452)
	at clojure.main$load_script.invokeStatic(main.clj:278)
	at clojure.main$init_opt.invokeStatic(main.clj:280)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invokeStatic(main.clj:311)
	at clojure.main$null_opt.invokeStatic(main.clj:345)
	at clojure.main$null_opt.invoke(main.clj:342)
	at clojure.main$main.invokeStatic(main.clj:424)
	at clojure.main$main.doInvoke(main.clj:387)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.main.main(main.java:37)
Caused by: clojure.lang.ExceptionInfo: Call to clojure.core/defn did not conform to spec:
In: [2 0] val: {:keys [type user password realm preemptive], :or {:type :basic}} fails spec: :clojure.core.specs.alpha/arg-list at: [:args :bs :arity-n :bodies :args] predicate: vector?
In: [2 0] val: ({:keys [type user password realm preemptive], :or {:type :basic}} b) fails spec: :clojure.core.specs.alpha/arg-list at: [:args :bs :arity-1 :args] predicate: (cat :args (* :clojure.core.specs.alpha/binding-form) :varargs (? (cat :amp #{(quote &)} :form :clojure.core.specs.alpha/binding-form))),  Extra input
 {:clojure.spec.alpha/problems ({:path [:args :bs :arity-1 :args], :reason "Extra input", :pred (clojure.spec.alpha/cat :args (clojure.spec.alpha/* :clojure.core.specs.alpha/binding-form) :varargs (clojure.spec.alpha/? (clojure.spec.alpha/cat :amp #{(quote &)} :form :clojure.core.specs.alpha/binding-form))), :val ({:keys [type user password realm preemptive], :or {:type :basic}} b), :via [:clojure.core.specs.alpha/defn-args :clojure.core.specs.alpha/args+body :clojure.core.specs.alpha/arg-list :clojure.core.specs.alpha/arg-list], :in [2 0]} {:path [:args :bs :arity-n :bodies :args], :pred clojure.core/vector?, :val {:keys [type user password realm preemptive], :or {:type :basic}}, :via [:clojure.core.specs.alpha/defn-args :clojure.core.specs.alpha/args+body :clojure.core.specs.alpha/args+body :clojure.core.specs.alpha/args+body :clojure.core.specs.alpha/arg-list :clojure.core.specs.alpha/arg-list], :in [2 0]}), :clojure.spec.alpha/spec #object[clojure.spec.alpha$regex_spec_impl$reify__1188 0xfd8513b "clojure.spec.alpha$regex_spec_impl$reify__1188@fd8513b"], :clojure.spec.alpha/value (set-realm "Sets realm on builder." [{:keys [type user password realm preemptive], :or {:type :basic}} b] (let [rbld (Realm$RealmBuilder.)] (.setScheme rbld (type->auth-scheme type)) (when (nil? user) (if (nil? password) (throw (IllegalArgumentException. "For authentication user and password is required")) (throw (IllegalArgumentException. "For authentication user is required")))) (when (nil? password) (throw (IllegalArgumentException. "For authentication password is required"))) (when (= :digest type) (when (nil? realm) (throw (IllegalArgumentException. "For DIGEST authentication realm is required"))) (.setRealmName rbld realm)) (when-not (nil? preemptive) (.setUsePreemptiveAuth rbld preemptive)) (doto rbld (.setPrincipal user) (.setPassword password)) (.setRealm b (.build rbld)))), :clojure.spec.alpha/args (set-realm "Sets realm on builder." [{:keys [type user password realm preemptive], :or {:type :basic}} b] (let [rbld (Realm$RealmBuilder.)] (.setScheme rbld (type->auth-scheme type)) (when (nil? user) (if (nil? password) (throw (IllegalArgumentException. "For authentication user and password is required")) (throw (IllegalArgumentException. "For authentication user is required")))) (when (nil? password) (throw (IllegalArgumentException. "For authentication password is required"))) (when (= :digest type) (when (nil? realm) (throw (IllegalArgumentException. "For DIGEST authentication realm is required"))) (.setRealmName rbld realm)) (when-not (nil? preemptive) (.setUsePreemptiveAuth rbld preemptive)) (doto rbld (.setPrincipal user) (.setPassword password)) (.setRealm b (.build rbld))))}
	at clojure.core$ex_info.invokeStatic(core.clj:4744)
	at clojure.core$ex_info.invoke(core.clj:4744)
	at clojure.spec.alpha$macroexpand_check.invokeStatic(alpha.clj:689)
	at clojure.spec.alpha$macroexpand_check.invoke(alpha.clj:681)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.lang.Compiler.checkSpecs(Compiler.java:6889)
	... 241 more
Tests failed
```

The issue is with the `[clj-campfire "2.2.0"]` dependency. This dependency use an old version of [http.async.client](https://github.com/cch1/http.async.client), with this [bug](https://github.com/cch1/http.async.client/pull/76).

We should : 

- Force the http.async.client version in Riemann project.clj to 1.2.0
- Or remove the campfire integration. (campfire is now basecamp if i understand correctly [this](https://basecamp.com/retired/campfire)).

I personally prefer the second solution if no one use the campfire integration.

**Comment by jamtur01** [comment]
Want to ask in riemann-users if anyone uses it and if no one pings let's deprecate it?

**Comment by mcorbin** [comment]
Done ;) I will remove the campfire dependency if i have no answer to my email.

**Comment by jamtur01** [comment]
Let's kill it. :)

**Comment by faxm0dem** [comment]
🏕 🔥
