### ISSUE TITLE
Issue when updating com.cemerick/pomegranate

### ISSUE THREAD

**Issue by mcorbin** [riemann/riemann#890]
pomegranate has been updated to support JDK9 (cf [the changelog](https://github.com/cemerick/pomegranate/blob/master/CHANGES.md)). When i upgrade Riemann with pomegranade 1.0.0 i have this error at start:

```

ERROR [2017-12-16 22:13:54,845] main - riemann.bin - Couldn't start
java.lang.IllegalStateException: Could not find a suitable classloader to modify from clojure.lang.LazySeq@9d3e1dd0
	at cemerick.pomegranate$add_classpath.invokeStatic(pomegranate.clj:54)
	at cemerick.pomegranate$add_classpath.invoke(pomegranate.clj:42)
	at riemann.bin$set_config_file_BANG_.invokeStatic(bin.clj:31)
	at riemann.bin$set_config_file_BANG_.invoke(bin.clj:18)
	at riemann.bin$_main.invokeStatic(bin.clj:119)
	at riemann.bin$_main.doInvoke(bin.clj:108)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at riemann.bin.main(Unknown Source)
```

We should probably fix it before merging the JDK9 PR.

**Comment by jamtur01** [comment]
See:
https://github.com/cemerick/pomegranate#urlclassloader-modifiability
https://github.com/tobias/dynapath#note-on-urlclassloader
