### ISSUE TITLE
InfluxDB: field type conflict on "riemann executor agg accepted rate"

### ISSUE THREAD

**Issue by timgilbert** [riemann/riemann#898]
Hi! I'm running riemann 0.2.14 against influxdb 1.4.2 on Ubuntu yakkety. I've based my setup on [this blog post](http://acidwords.com/posts/2016-02-28-installing-grafana-riemann-and-influxdb.html). My config file isn't super complex:

```clojure
(def influxdb-creds {:host    "localhost"
                     :port    8086
                     :db      "riemann"})

(logging/init {:file "/var/log/riemann/riemann.log"})

(def influxBatchSender
    (batch 100 1/10
           (async-queue! :agg {:queue-size      1000
                               :core-pool-size  1
                               :max-pool-size   4
                               :keep-alive-time 60000}
                         (influxdb influxdb-creds))))

(let [host "0.0.0.0"]
  (tcp-server {:host host}))

; Expire old events from the index every 5 seconds.
(periodically-expire 60)

(let [index (index)]
  (streams
    (default :ttl 60
      ; Index all events immediately.
      index
      #(info %)
      influxBatchSender)))
```

When I run riemann, I'm seeing tons of these error messages in the logs:

```
WARN [2018-01-03 23:20:40,845] pool-1-thread-1 - riemann.streams - riemann.influxdb$influxdb_deprecated$streams__9726@7c1c47e2 threw
java.lang.RuntimeException: {"error":"partial write: field type conflict: input field \"value\" on measurement \"riemann executor agg accepted rate\" is type float, already exists as type integer dropped=2"}

	at org.influxdb.impl.InfluxDBImpl.execute(InfluxDBImpl.java:266)
	at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:167)
	at riemann.influxdb$write_batch_point.invokeStatic(influxdb.clj:182)
	at riemann.influxdb$write_batch_point.invoke(influxdb.clj:179)
	at riemann.influxdb$influxdb_deprecated$streams__9726.invoke(influxdb.clj:253)
	at riemann.streams$execute_on$stream__7093$runner__7094$fn__7099.invoke(streams.clj:268)
	at riemann.streams$execute_on$stream__7093$runner__7094.invoke(streams.clj:268)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:646)
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1881)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1881)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invokeStatic(core.clj:650)
	at clojure.core$bound_fn_STAR_$fn__4671.doInvoke(core.clj:1911)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

The offending data seems to be this one:

```
INFO [2018-01-03 23:32:51,363] Thread-7 - riemann.config - #riemann.codec.Event{:host ip-172-31-70-200, :service riemann executor agg completed rate, :state ok, :description nil, :metric 200/2001, :tags [riemann], :time 1515022371361/1000, :ttl 20}
```

I wonder if this could be related to Clojure fractional-number handling, like maybe the first data point evaluates as `1/1` and is stored as an `integer`?

From a scan of the issues this might possibly be related to #848? I've tried dropping and recreating the InfluxDB database, but it doesn't seem to have any effect.

**Comment by mcorbin** [comment]
Hi,

It's probably the same bug that #848. I reproduce it locally with your configuration:

```
INFO [2018-01-04 00:58:09,825] Thread-7 - riemann.config - #riemann.codec.Event{:host mcorbin, :service riemann executor agg accepted rate, :state ok, :description nil, :metric 0N, :tags [riemann], :time 1515023889791/1000, :ttl 20}
INFO [2018-01-04 00:58:19,868] Thread-7 - riemann.config - #riemann.codec.Event{:host mcorbin, :service riemann executor agg accepted rate, :state ok, :description nil, :metric 500/5023, :tags [riemann], :time 1515023899837/1000, :ttl 20}
java.lang.RuntimeException: {"error":"partial write: field type conflict: input field \"value\" on measurement \"riemann executor agg accepted rate\" is type float, already exists as type integer dropped=2"}
```
I tested your configuration with Riemann master (so with my fix for #848), and had no error. You can build Riemann using [leiningen](https://leiningen.org/) if you want to try it yourself (just do `lein uberjar` and use the standalone jar in the `target` directory).

Btw, it's recommended to use [this syntax](http://riemann.io/howto.html#forward-to-influxdb), with the `:version :new-stream` option when you forward events to InfluxDB (the old influxdb stream is deprecated). Don't hesitate to ask questions if you need help configuring Riemann ;)

**Comment by timgilbert** [comment]
Thanks for the tip @mcorbin.

FWIW, I updated my config to use `:version :new-stream` as you suggested, and now I'm seeing a NullPointerException instead of the previous error.

```
WARN [2018-01-04 01:37:18,256] pool-1-thread-1 - riemann.streams - riemann.influxdb$influxdb_new_stream$streams__9716@3b45ac3b threw
java.lang.NullPointerException: null
	at org.influxdb.dto.BatchPoints.point(BatchPoints.java:194)
	at riemann.influxdb$get_batchpoints$fn__9701$fn__9706.invoke(influxdb.clj:198)
	at riemann.influxdb$get_batchpoints$fn__9701.invoke(influxdb.clj:198)
	at clojure.core$map$fn__4785.invoke(core.clj:2646)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:521)
	at clojure.core$seq__4357.invokeStatic(core.clj:137)
	at clojure.core$seq__4357.invoke(core.clj:137)
	at riemann.influxdb$influxdb_new_stream$streams__9716.invoke(influxdb.clj:230)
	at riemann.streams$execute_on$stream__7093$runner__7094$fn__7099.invoke(streams.clj:268)
	at riemann.streams$execute_on$stream__7093$runner__7094.invoke(streams.clj:268)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:646)
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1881)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1881)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invokeStatic(core.clj:650)
	at clojure.core$bound_fn_STAR_$fn__4671.doInvoke(core.clj:1911)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

I'm not certain which of the inputs caused this, I see a lot of nil values in there though. As before, I tried dropping the database from `influx` and restarting but got the same behavior.

At this point I'll probably just wait for a riemann release that picks up your change. Thanks!

```
INFO [2018-01-04 01:39:51,977] Thread-7 - riemann.config - #riemann.codec.Event{:host my-hostname, :service riemann streams rate, :state nil, :description nil, :metric 0.0, :tags [riemann], :time 1515029991953/1000, :ttl 20}
INFO [2018-01-04 01:39:51,982] Thread-7 - riemann.config - #riemann.codec.Event{:host my-hostname, :service riemann streams latency 0.0, :state nil, :description nil, :metric nil, :tags [riemann], :time 1515029991953/1000, :ttl 20}
INFO [2018-01-04 01:39:51,982] Thread-7 - riemann.config - #riemann.codec.Event{:host my-hostname, :service riemann streams latency 0.5, :state nil, :description nil, :metric nil, :tags [riemann], :time 1515029991953/1000, :ttl 20}
INFO [2018-01-04 01:39:51,982] Thread-7 - riemann.config - #riemann.codec.Event{:host my-hostname, :service riemann streams latency 0.95, :state nil, :description nil, :metric nil, :tags [riemann], :time 1515029991953/1000, :ttl 20}
INFO [2018-01-04 01:39:51,983] Thread-7 - riemann.config - #riemann.codec.Event{:host my-hostname, :service riemann streams latency 0.99, :state nil, :description nil, :metric nil, :tags [riemann], :time 1515029991953/1000, :ttl 20}
INFO [2018-01-04 01:39:51,983] Thread-7 - riemann.config - #riemann.codec.Event{:host my-hostname, :service riemann streams latency 0.999, :state nil, :description nil, :metric nil, :tags [riemann], :time 1515029991953/1000, :ttl 20}
INFO [2018-01-04 01:39:51,983] Thread-7 - riemann.config - #riemann.codec.Event{:host my-hostname, :service riemann netty event-executor threads active, :state ok, :description nil, :metric 2, :tags [riemann], :time 757514995977/500, :ttl 20}
INFO [2018-01-04 01:39:51,984] Thread-7 - riemann.config - #riemann.codec.Event{:host my-hostname, :service riemann netty event-executor queue size, :state ok, :description nil, :metric 0, :tags [riemann], :time 757514995977/500, :ttl 20}
INFO [2018-01-04 01:39:51,984] Thread-7 - riemann.config - #riemann.codec.Event{:host my-hostname, :service riemann index size, :state ok, :description nil, :metric 0, :tags nil, :time 303005998391/200, :ttl 20}
INFO [2018-01-04 01:39:51,984] Thread-7 - riemann.config - #riemann.codec.Event{:host my-hostname, :service riemann executor agg accepted rate, :state ok, :description nil, :metric 0N, :tags [riemann], :time 378757497989/250, :ttl 20}
INFO [2018-01-04 01:39:51,985] Thread-7 - riemann.config - #riemann.codec.Event{:host my-hostname, :service riemann executor agg completed rate, :state ok, :description nil, :metric 0N, :tags [riemann], :time 378757497989/250, :ttl 20}
INFO [2018-01-04 01:39:51,985] Thread-7 - riemann.config - #riemann.codec.Event{:host my-hostname, :service riemann executor agg rejected rate, :state ok, :description nil, :metric 0N, :tags [riemann], :time 378757497989/250, :ttl 20}
INFO [2018-01-04 01:39:51,985] Thread-7 - riemann.config - #riemann.codec.Event{:host my-hostname, :service riemann executor agg queue capacity, :state ok, :description nil, :metric 1000, :tags [riemann], :time 378757497989/250, :ttl 20}
INFO [2018-01-04 01:39:51,986] Thread-7 - riemann.config - #riemann.codec.Event{:host my-hostname, :service riemann executor agg queue size, :state ok, :description nil, :metric 0, :tags [riemann], :time 378757497989/250, :ttl 20}
INFO [2018-01-04 01:39:51,986] Thread-7 - riemann.config - #riemann.codec.Event{:host my-hostname, :service riemann executor agg queue used, :state ok, :description nil, :metric 0, :tags [riemann], :time 378757497989/250, :ttl 20}
INFO [2018-01-04 01:39:51,986] Thread-7 - riemann.config - #riemann.codec.Event{:host my-hostname, :service riemann executor agg threads active, :state ok, :description nil, :metric 0, :tags [riemann], :time 378757497989/250, :ttl 20}
INFO [2018-01-04 01:39:51,986] Thread-7 - riemann.config - #riemann.codec.Event{:host my-hostname, :service riemann executor agg threads alive, :state ok, :description nil, :metric 0, :tags [riemann], :time 378757497989/250, :ttl 20}
INFO [2018-01-04 01:39:51,987] Thread-7 - riemann.config - #riemann.codec.Event{:host my-hostname, :service riemann server tcp 0.0.0.0:5555 conns, :state ok, :description nil, :metric 1, :tags [riemann], :time 757514995979/500, :ttl 20}
INFO [2018-01-04 01:39:51,987] Thread-7 - riemann.config - #riemann.codec.Event{:host my-hostname, :service riemann server tcp 0.0.0.0:5555 in rate, :state ok, :description nil, :metric 0.0, :tags [riemann], :time 757514995979/500, :ttl 20}
INFO [2018-01-04 01:39:51,987] Thread-7 - riemann.config - #riemann.codec.Event{:host my-hostname, :service riemann server tcp 0.0.0.0:5555 in latency 0.0, :state ok, :description nil, :metric nil, :tags [riemann], :time 757514995979/500, :ttl 20}
INFO [2018-01-04 01:39:51,988] Thread-7 - riemann.config - #riemann.codec.Event{:host my-hostname, :service riemann server tcp 0.0.0.0:5555 in latency 0.5, :state ok, :description nil, :metric nil, :tags [riemann], :time 757514995979/500, :ttl 20}
INFO [2018-01-04 01:39:51,988] Thread-7 - riemann.config - #riemann.codec.Event{:host my-hostname, :service riemann server tcp 0.0.0.0:5555 in latency 0.95, :state ok, :description nil, :metric nil, :tags [riemann], :time 757514995979/500, :ttl 20}
INFO [2018-01-04 01:39:51,989] Thread-7 - riemann.config - #riemann.codec.Event{:host my-hostname, :service riemann server tcp 0.0.0.0:5555 in latency 0.99, :state ok, :description nil, :metric nil, :tags [riemann], :time 757514995979/500, :ttl 20}
INFO [2018-01-04 01:39:51,989] Thread-7 - riemann.config - #riemann.codec.Event{:host my-hostname, :service riemann server tcp 0.0.0.0:5555 in latency 0.999, :state ok, :description nil, :metric nil, :tags [riemann], :time 757514995979/500, :ttl 20}
```

**Comment by mcorbin** [comment]
You should use the new event format for influxdb (cf the Riemann howto). with :measurement, :influxdb-tags, :influxdb-fields keys.  Example:

```clojure

(def influxBatchSender
  (smap (fn [event]
          (assoc event :measurement     (:service event)
                 :influxdb-tags   {:state (:state event)}
                 ;; :value = 0 by default
                 :influxdb-fields {:value (or (:metric event) 0)}))
        (batch 100 1/10
               (async-queue! :agg {:queue-size      1000
                                   :core-pool-size  1
                                   :max-pool-size   4
                                   :keep-alive-time 60000}
                             (influxdb influxdb-creds)))))
```

Regarding your first issue, if you don't want to wait for the first Riemann release, you can converts the :metric field to double (that's sort of what my patch did). So the full code will be:

```clojure

(def influxdb-creds {:host    "localhost"
                     :port    8086
                     :db      "riemann"
                     :version :new-stream})

(def influxBatchSender
   (smap (fn [event]
           (assoc event :measurement     (:service event)
                  :influxdb-tags   {:state (:state event)}
                  ;; :value = 0 by default, + converts to double
                  :influxdb-fields {:value (double (or (:metric event) 0))}))
         (batch 100 1/10
                (async-queue! :agg {:queue-size      1000
                                    :core-pool-size  1
                                    :max-pool-size   4
                                    :keep-alive-time 60000}
                              (influxdb influxdb-creds)))))
```

With this code, everything should work (:new stream version + :metric cast to double).

**Comment by timgilbert** [comment]
Thanks @mcorbin, using that code got rid of the log messages.
