### ISSUE TITLE
Could not find a suitable classloader to modify from clojure.lang.LazySeq

### ISSUE THREAD

**Issue by 42alex** [riemann/riemann#914]
I'm trying to load an empty custom config file with 
```
(riemann-test/with-test-env
(set-config-file! "etc/oms.riemann.rules.clj")...)
```
i'm getting an arcane exception:
```
Exception in thread "main" java.lang.IllegalStateException: Could not find a suitable classloader to modify from clojure.lang.LazySeq@146ee38c, compiling:(/private/var/folders/49/0bhyzws16xq36w1zrh756p9w0000gp/T/form-init2022898044782769951.clj:1:125)
        at clojure.lang.Compiler.load(Compiler.java:7526)
        at clojure.lang.Compiler.loadFile(Compiler.java:7452)
        at clojure.main$load_script.invokeStatic(main.clj:278)
        at clojure.main$init_opt.invokeStatic(main.clj:280)
        at clojure.main$init_opt.invoke(main.clj:280)
        at clojure.main$initialize.invokeStatic(main.clj:311)
        at clojure.main$null_opt.invokeStatic(main.clj:345)
        at clojure.main$null_opt.invoke(main.clj:342)
        at clojure.main$main.invokeStatic(main.clj:424)
        at clojure.main$main.doInvoke(main.clj:387)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:702)
        at clojure.main.main(main.java:37)
Caused by: java.lang.IllegalStateException: Could not find a suitable classloader to modify from clojure.lang.LazySeq@146ee38c
        at cemerick.pomegranate$add_classpath.invokeStatic(pomegranate.clj:54)
        at cemerick.pomegranate$add_classpath.invoke(pomegranate.clj:42)
        at riemann.bin$set_config_file_BANG_.invokeStatic(bin.clj:32)
        at riemann.bin$set_config_file_BANG_.invoke(bin.clj:19)
        at rimoms.riemann_adapter$do_test$fn__2473.invoke(riemann_adapter.clj:45)
        at clojure.core$with_redefs_fn.invokeStatic(core.clj:7434)
        at clojure.core$with_redefs_fn.invoke(core.clj:7418)
        at rimoms.riemann_adapter$do_test.invokeStatic(riemann_adapter.clj:41)
        at rimoms.riemann_adapter$do_test.doInvoke(riemann_adapter.clj:36)
        at clojure.lang.RestFn.invoke(RestFn.java:410)
        at rimoms.riemann_adapter$do_test.invokeStatic(riemann_adapter.clj:38)
        at rimoms.riemann_adapter$do_test.invoke(riemann_adapter.clj:36)
        at clojure.lang.Var.invoke(Var.java:377)
        at user$eval516.invokeStatic(form-init2022898044782769951.clj:1)
        at user$eval516.invoke(form-init2022898044782769951.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:7062)
        at clojure.lang.Compiler.eval(Compiler.java:7052)
        at clojure.lang.Compiler.load(Compiler.java:7514)
```
What am i doing wrong?

**Comment by jamtur01** [comment]
What Java version are you using?

**Comment by 42alex** [comment]
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

**Comment by mcorbin** [comment]
Hi,

You can try to call `(ensure-dynamic-classloader)` from riemann.bin before `set-config-file!`. 
What are you trying to do exactly ? Do you want to use this code in your riemann.config file ?

**Comment by 42alex** [comment]
I built a wrapper around riemann for our environment. One command would test the rules provided in a config file:

```
(defn do-test
  ([]
   (do-test (cfg/get-config :riemann-config-file)))
  ([config & test-name]
   (try
     (riemann-test/with-test-env
       (println "(re)loading config")
       (if-not (realized? config-file)
         (do (println "loading " config)
             (ensure-dynamic-classloader)
             (set-config-file! config)
             (riemann.config/include @config-file)))
      (binding [riemann-test/*core* @config/core]
         (let [test-name-pattern (if test-name (re-pattern test-name) #".*-test")
                results (run-tests test-name-pattern)]
           (if (and (zero? (:error results))
                    (zero? (:fail results)))
             (println "SUCCESS")
             (println "ERROR"))
           ))))))
```

The test: 

```
(deftest should-print-logme-tagged-events
           (println "TESTING!0")
           ;; inject in foo-stream only
           (let [result (inject! [{:host "OMS"
                                   :time 1
                                   :service "UNKNOWN_WHATEVER_SERVICE"
                                   :message "set-cs-suborder-status!"
                                   :ttl 100                 ;2 h
                                   :tags ["logme"]
                                   :metric 10}])]
             (println (format "all taps: %s" result))
             (is (= [{:host "OMS"
                      :time 1
                      :service "UNKNOWN_WHATEVER_SERVICE"
                      :message "set-cs-suborder-status!"
                      :ttl 100                              ;2 h
                      :tags ["logme"]
                      :metric 10}]
                    (:log-info result)))))
```
the rule: 
```
(require
  '[rimoms.config :refer [get-config]]
  '[riemann.streams :refer :all]
  '[riemann.test :refer :all]
  '[riemann.config :refer :all]
  '[riemann.email :refer [mailer]]
  '[riemann.hipchat :refer [hipchat]]
  ;'[riemann.transport.tcp :refer [tcp-server]]
  ;'[riemann.transport.udp :refer [udp-server]]
  '[riemann.logging :as logging]
  '[clojure.tools.logging :as log]
  '[cheshire.core :as json])
(def log-info
  (tap :log-info (io #(log/info (json/generate-string %)))))
(let [index (index)] 
  (streams
    (tap :all (default :ttl 60 
                       (tap :index index)
                       (where (tagged "logme")
                              log-info)))))
```

the test `should-print-logme-tagged-events` fails now as do all other tests.
All taps appear to be empty according to the test message:

```
all taps: { :log-info [], :all [], :index []}

```

The same rule/loading system did still work with riemann "0.2.13".

**Comment by mcorbin** [comment]
I refactored a lot of things for tests in 0.3.0.
Maybe this line could help : https://github.com/riemann/riemann/blob/master/src/riemann/bin.clj#L141
You can check riemann.bin to see the changes.
